version: "3"
services:
    l_echo:
        image: badmathematician/echo_redis
        command: bash -c "service redis-server start && cd laravel-echo-server/ && laravel-echo-server client:add && laravel-echo-server start --dir=/laravel-echo-server"
        volumes:
            - /home/mykola/work/laravel/test2/app/Packages/LaravelEchoServer/src/echo/:/laravel-echo-server
