version: "3"
services:
    l_echo:
        image: badmathematician/laravel-echo-server
        command: bash -c "service redis-server start  && service supervisor start && cd laravel-echo-server/ && laravel-echo-server client:add &&  tail -f "
        volumes:
            - $HOME/echo:/laravel-echo-server
