version: "3"
services:
    l_echo:
        image: badmathematician/laravel-echo-server
        command: bash -c "service redis-server start
                 && cd laravel-echo-server/
                 && laravel-echo-server client:add
                 && service supervisor start
                 && tail -f /laravel-echo-server/laravel-echo-server-supervisor.log"
        volumes:
            - $HOME/echo:/laravel-echo-server
